### PR TITLE
Catch serializer initialization error

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by jasisk** [comment]
Why not catch [here](https://github.com/aredridel/spud/blob/9b44cbe679470b68e6c60b346b493326d0af99f5/lib/serializer/serializerFactory.js#L32) instead?

**Comment by aredridel** [comment]
Because that, too, has a synchronous interface. And its caller, too.

**Comment by aredridel** [comment]
(and the internals are still unbelievably ugly due to flexibility we're not using)

**Comment by jasisk** [comment]
😵

**Pull request merged**
