### PR TITLE
debounce callback in a less clever, less meaningful, but actually functioning way

### PR DESCRIPTION
**Pull request by aredridel**

### CODE REVIEW

**Comment by pvenkatakrishnan** [comment]
:+1:

**Comment by totherik** [comment]
I _think_ this looks good... :+1:

**Comment by jasisk** [comment]
Three thinks makes a right. Right? :+1:

**Comment by aredridel** [comment]
Alright then! If it explodes, I'll wipe the soot from my hands on both of you.

**Pull request merged**
